[versions]
minecraft = "1.20.4"
yarn_mappings = "1.20.4+build.3"
fabric_loader = "0.18.4"
loom = "1.15-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
